create table if not exists public.portfolio_metric_snapshots (
  id bigint generated by default as identity primary key,
  projet text not null,
  nom text not null,
  mrr numeric not null default 0 check (mrr >= 0),
  comptes_actifs bigint not null default 0 check (comptes_actifs >= 0),
  statut_sante text not null default 'unknown' check (statut_sante in ('healthy','warning','critical','unknown')),
  details jsonb not null default '{}'::jsonb,
  captured_at timestamptz not null default now()
);

create index if not exists portfolio_metric_snapshots_project_time_idx
  on public.portfolio_metric_snapshots (projet, captured_at desc);

alter table public.portfolio_metric_snapshots enable row level security;
revoke all on public.portfolio_metric_snapshots from anon, authenticated;
