create table if not exists public.portfolio_metric_snapshots (
  id bigint generated by default as identity primary key,
  projet text not null,
  nom text not null,
  mrr bigint not null default 0 check (mrr >= 0),
  comptes_actifs bigint not null default 0 check (comptes_actifs >= 0),
  statut_sante text not null default 'unknown' check (statut_sante in ('healthy','warning','critical','unknown')),
  details jsonb not null default '{}'::jsonb,
  captured_at timestamptz not null default now()
);

create index if not exists portfolio_metric_snapshots_project_time_idx
  on public.portfolio_metric_snapshots (projet, captured_at desc);

alter table public.portfolio_metric_snapshots enable row level security;
revoke all on public.portfolio_metric_snapshots from anon, authenticated;

create table if not exists public.project_intelligence_items (
  id bigint generated by default as identity primary key,
  projet text not null,
  kind text not null check (kind in ('anomaly','attention','recommendation','review')),
  severity text not null default 'info' check (severity in ('info','warning','critical')),
  title text not null,
  message text not null,
  source text not null default 'control_center',
  status text not null default 'open' check (status in ('open','acknowledged','resolved')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists project_intelligence_items_project_status_idx
  on public.project_intelligence_items (projet, status, created_at desc);

alter table public.project_intelligence_items enable row level security;
revoke all on public.project_intelligence_items from anon, authenticated;